<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJRHgKXn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJRHgKXn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJRHgKXn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJRHgKXn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJRHgKXn\App_KernelDevDebugContainer([
    'container.build_hash' => 'JRHgKXn',
    'container.build_id' => '25f4efa0',
    'container.build_time' => 1583501412,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJRHgKXn');
